name: Validation

on: push 

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: bahmutov/npm-install@v1.4.5
      - name: Install dependencies
        run: yarn install
      - name: Mocha
        run: yarn test:ci --coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
